library(dplyr)
source("scripts/gcd.R")


# input is ngram vector
learn_from_trigrams <- function(ngram){ 
  model <- list()
  for(i in 1: length(ngram)){
    rw <- ngram[i]
    str_vec <- strsplit(rw ,split=',', fixed=TRUE)[[1]] # e.g. [1] "99"   "at"   "the"  "time" "522"
    key <- paste(str_vec[2], str_vec[3], sep = " ")  #paste(rw$word1, rw$word2, sep = " ")
    val <- paste(rep(str_vec[4], strtoi(vec[5])), collapse = " ")  #paste(rep(rw$word3, rw$n), collapse = " ")
      
    cur_val <- model[[key]]
    if(is.null(cur_val)){
      # new entry
      model[key] = val
    }else{
      model[key] = paste(c(cur_val, val), collapse = " ")
    }

    if(i%%1000 == 0){
      print(i) # for visual inspection
    }

  }
  model
}

learn_from_bigrams <- function(ngram){ 
  model <- list()
  for(i in 2: length(ngram)){ #skip header
  #for(i in 2: 1000){
    rw <- ngram[i]
    str_vec <- strsplit(rw ,split=',', fixed=TRUE)[[1]] # e.g. [1] "99"   "at"   "the"  "time" "522"
    key <- str_vec[2]  #paste(rw$word1, rw$word2, sep = " ")
    
    n <- strtoi(str_vec[4])
    if(is.na(n))
      next
    
    val <- paste(rep(str_vec[3], strtoi(str_vec[4])), collapse = " ")  #paste(rep(rw$word3, rw$n), collapse = " ")
    
    cur_val <- model[[key]]
    if(is.null(cur_val)){
      # new entry
      model[key] = val
    }else{
      model[key] = paste(c(cur_val, val), collapse = " ")
    }
    
    if(i%%1000 == 0){
      print(i) # for visual inspection
    }
    
  }
  model
}

predict_next_word <- function(){
  
}

#bigrams <- readRDS("bigrams.rds")
#trigrams <- readRDS("trigrams.rds")
#ngrams_model <- learn_from_ngrams(bigrams, trigrams)
#next_word <- predict_next_word(ngrams_model, "thanks for")

# generating trigram model
trigrams <- readRDS("trigrams.rds") # Read trigrams.rds generated by eda.R into dataframe
write.csv(trigrams, file="trigrams.csv", quote=FALSE) # Write trigrams dataframe to CSV
sample_text("trigrams.csv", "trigrams_sample.csv") # Sampling of trigrams CSV (to .1)
trigrams_sample <- readLines("trigrams_sample.csv") # Read sample into vector
trigrams_model <- learn_from_trigrams(trigrams_sample) # from sample vector, learn the model, which is just a List.
save(trigrams_model, file="trigrams_model.RData") # save the trigram model to disk
load("trigrams_model.RData") # load trigram model

# generating bigram model
bigrams <- readRDS("bigrams.rds")
write.csv(bigrams, file="bigrams.csv", quote=FALSE)
sample_text("bigrams.csv", "bigrams_sample.csv")
bigrams_sample <- readLines("bigrams_sample.csv")
bigrams_model <- learn_from_bigrams(bigrams_sample)
save(bigrams_model, file="bigrams_model.RData") 
load("bigrams_model.RData")
